let code1;
code1 = 7 + 3;
let code2 = 40 / 1 - 0;
let code3 = (80 % 3) + 37;
const message = "The vault has been secured. The combination is:";
const codeA = code1 + "-" + code2 + "-" + code3;
console.log(codeA);
const codeB = `${code1}-${code2}-${code3}`;
console.log(codeB);
console.log(`${message} ${codeA} ${codeB}`);
